### ISSUE TITLE
Balls ItemIDs so I can add them to BetterTeleporter keep list

### ISSUE THREAD

**Issue by Overvault-64** [Feiryn/LethalMon#14]
I use [BetterTeleporter](https://thunderstore.io/c/lethal-company/p/SirTyler/BetterTeleporter/) to prevent certain items from being removed from my inventory when teleported.
The exclusion list is based on item IDs so I'm wondering what are the IDs of the various balls so I can add them to the list.
I've already tried the most obvious ones (`Pokeball`, `Greatball`, `Ultraball`, `Masterball`) but didn't work.
![image](https://github.com/user-attachments/assets/8539ad06-8738-40eb-9380-13fdd560579e)
Please advise

**Comment by Feiryn** [comment]
I've looked at the code of BetterTeleporter and it should be the ones you tried.
Maybe you can try PokeballItem for all the balls.

If it doesn't work, I'll debug this on Sunday

**Comment by Overvault-64** [comment]
Unfortunately `PokeballItem` didn't work :(

**Comment by NiroDev** [comment]
Looked it up and BetterTeleport uses GetType(), which returns the class type.
For our items this is
- LethalMon.Items.Pokeball
- LethalMon.Items.Greatball
- LethalMon.Items.Ultraball
- LethalMon.Items.Masterball

**Comment by Overvault-64** [comment]
> * LethalMon.Items.Pokeball
> * LethalMon.Items.Greatball
> * LethalMon.Items.Ultraball
> * LethalMon.Items.Masterball

YES it works!
For other users, just add the following string to `KeepItemListInverse` and `KeepItemListInverse` in `BepInEx\config\BetterTeleporter.cfg`:
```
,LethalMon.Items.Pokeball,LethalMon.Items.Greatball,LethalMon.Items.Ultraball,LethalMon.Items.Masterball
```
