### ISSUE TITLE
Balls are clipping

### ISSUE THREAD

**Issue by Feiryn** [Feiryn/LethalMon#17]
I got multiple reports that balls are clipping sometimes.
I can't manage to reproduce it.
It is maybe because of a mod incompatibility

**Comment by jwols123** [comment]
I have this same problem, it may be a mod incompatibility. I just need to drop/throw it and it sometimes happens.

**Comment by Feiryn** [comment]
> I have this same problem, it may be a mod incompatibility. I just need to drop/throw it and it sometimes happens.

Can you send me your modpack with r2modman export please?

**Comment by Feiryn** [comment]
Alright, I found the issue. It happens to users with low fps. Should be fixed in version 0.5.2 (released soon).
Fix in commit fc78a9f
