### ISSUE TITLE
Bracken can kill teammates

### ISSUE THREAD

**Issue by Feiryn** [Feiryn/LethalMon#18]
Some players reported that the bracken can kill the owner or the teammates, but I can't reproduce it

**Comment by NiroDev** [comment]
Happened to me twice in one game.
First occurence: I threw the ball with the bracken inside while running in the throw direction. It spawned inside of me and immediatly killed me at spawn.
Second occurence: It killed a crewmate at the entrance.

In both scenarios neither me nor the crewmate were the host.

**Comment by Feiryn** [comment]
Seems to be fixed as I didn't have any new bug report this
