### ISSUE TITLE
Baboon hawks sometimes switch back to tamed following after targeting a monster

### ISSUE THREAD

**Issue by Feiryn** [Feiryn/LethalMon#30]

**Comment by NiroDev** [comment]
They do so if the owner is too far away, as they like to stay close to their "group" (the owner)

**Comment by Feiryn** [comment]
> They do so if the owner is too far away, as they like to stay close to their "group" (the owner)

It actually happened while the baboon was like 2 meters away, close to the monster

**Comment by Feiryn** [comment]
Didn't appear again, will open again if it does
