### ISSUE TITLE
pokeballs changing or respawning

### ISSUE THREAD

**Issue by TicketedGore** [Feiryn/LethalMon#32]
when me and some buddies left the game yesterday we had 4 pokeballs 3 had stuff and a master chillin we loaded up today and only had a single lethalmon and a regular empty pokeball today

**Comment by Feiryn** [comment]
Can you load up the save and send here the logs afterward?

**Comment by TicketedGore** [comment]
ill have to see if it does it again on our save and get that for you to check it out

**Comment by Feiryn** [comment]
@JoshShareprod If the issue happens again, can you send me your save file or logs please? I can't reproduce the issue

**Comment by JoshShareprod** [comment]
Sorry long weekend and was away from my PC. I have two files but I can't link them on GitHub? Is there another way to send them?

**Comment by Feiryn** [comment]
> Sorry long weekend and was away from my PC. I have two files but I can't link them on GitHub? Is there another way to send them?

It is not needed anymore, some players found that the issue is caused by LethalLevelLoader and custom moons and dungeons.
I'm currently working on a fix
