### ISSUE TITLE
Stuck in Blackscreen when Loading Into the Ship

### ISSUE THREAD

**Issue by Xherdos** [Feiryn/LethalMon#45]
Happens with Version 0.5.4 (the Newest with the Slime being Catchable), don't know what broke but the Hud doesn't want to load partially, there is a "Grab" context and then nothing else.

![20240916113610_1](https://github.com/user-attachments/assets/f1a74c4c-06e0-4efb-ba52-6608b315600b)

**Comment by Feiryn** [comment]
Can you send me your logs file?

**Comment by Xherdos** [comment]
[LogOutput.log](https://github.com/user-attachments/files/17012065/LogOutput.log)


I hope that the right one.

**Comment by Feiryn** [comment]
I think that there is a mod conflict. A mod is duplicating enemies 15x for whatever reason. Can you send me your modpack exported with your mod manager?

**Comment by Xherdos** [comment]
0191fac9-eb14-cd86-36ef-fe8dde4ad90b

Yea there is the Code, many of the mods in there was added by a Friend.

**Comment by Feiryn** [comment]
I don't know which mod is conflicting but I found a fix. It will be fixed in version 0.5.5.
You can disable this mod while waiting for the release.

**Comment by Xherdos** [comment]
Thank you very much

**Comment by Feiryn** [comment]
Version 0.5.5 has been uploaded on the thunderstore and should be available in approximately 30 min
