### ISSUE TITLE
严重错误问题！

### ISSUE THREAD

**Issue by lenmon666** [Feiryn/LethalMon#52]
As long as you play, including third-party mod maps and official maps! This error message will appear as long as it is at 18:00 in the afternoon or during solar eclipse weather!
I have tried the latest version 0.6.3! I have also tried the old version and it still remains the same!
There is also a high chance of it occurring when playing alone!
When playing online with multiple players, the problem is 100% reproducible!
This error will cause frequent and large-scale error messages to refresh!
At the same time, it can cause frequent writing of log information to the local disk, resulting in intermittent lag issues in the game!
Could you please investigate the problem and provide a fix and update

**Comment by Feiryn** [comment]
Can you send me your mods list please?

**Comment by lenmon666** [comment]
> 你能把你的 Mod 列表发给我吗？
How can I send you a list of mods! Screenshot?

**Comment by lenmon666** [comment]
> 你能把你的 Mod 列表发给我吗？
BepInEx-BepInExPack-5.4.2100
notnotnotswipez-MoreCompany-1.10.1
FlipMods-ReservedItemSlotCore-2.0.37
anormaltwig-LateCompany-1.0.18
FlipMods-ReservedFlashlightSlot-2.0.8
x753-Mimics-2.6.4
FlipMods-ReservedWalkieSlot-2.0.6
tinyhoot-ShipLoot-1.1.0
Evaisa-HookGenPatcher-0.0.5
Evaisa-FixPluginTypesSerialization-1.1.1
MaxWasUnavailable-LethalModDataLib-1.2.2
Evaisa-LethalLib-0.16.1
Lordfirespeed-OdinSerializer-2022.11.9
xilophor-StaticNetcodeLib-1.1.1
FlipMods-HotbarPlus-1.8.0
FlipMods-BetterStamina-1.5.4
FlipMods-FasterItemDropship-1.3.1
fumiko-CullFactory-1.3.15
EladNLG-EladsHUD-1.3.0
ShaosilGaming-GeneralImprovements-1.4.4
Zaggy1024-PathfindingLagFix-1.4.0
CTNOriginals-CrossHair-1.1.2
Rune580-LethalCompany_InputUtils-0.7.7
Hardy-LCMaxSoundsFix-1.2.0
AudioKnight-StarlancerAIFix-3.8.3
AudioKnight-StarlancerMoons-2.4.0
AinaVT-LethalConfig-1.4.3
Dev1A3-LethalFixes-1.2.3
UnloadedHangar-LC16bitGraphicsRemove-0.2.9
DiFFoZ-HarmonyXTranspilerFix-1.1.0
DiFFoZ-LethalPerformance-0.4.0
JacobG5-ReverbTriggerFix-0.3.0
Noosh-AggresiveMaterialFix-1.0.3
DiFFoZ-BepInEx_Faster_Load_AssetBundles_Patcher-0.6.4
mattymatty-AsyncLoggers-2.1.2
DemonMae-ut99_interiors-1.2.12
LustrousLuna-Lunar_Lights-1.1.4
DarthLilo-LevelMusicLib-1.0.2
JacobG5-JLL-1.6.0
luakite-Vacuity_Moon-1.0.4
Boniato-Ganimedes-2.6.0
DiFFoZ-CompanyCruiserFix-1.0.5
IAmBatby-LethalToolbox-1.0.4
Zehs-ToilHead-1.7.2
Zehs-Toilation-1.0.2
chill73-CoconutMall-2.1.1
Spookily-Hawalia-1.1.0
WillowPillows-5_Tandraus-1.1.3
MrUnrealTeam-SchoolMoon-1.2.1
sfDesat-Aquatis-2.2.3
Magic_Wesley-Asteroid13-3.0.9
AboveFire-ShowMoonPriceLLL-1.1.2
DemonMae-unreal_interiors-1.6.10
Wexop-ColorfulJarOfPickles-1.0.5
mrgrm7-LethalCasino-0.5.5
silhygames-FumoCompany-1.3.1
qwcan-UmaCompany-3.1.0
ButteryStancakes-ButteryFixes-1.10.2
mattymatty-Matty_Fixes_Experimental-1.1.24
Magic_Wesley-WesleysInteriors-1.4.6
cl1ck-Xen_Interior-0.3.3
YippieDev-LethalApertureDunGen-1.1.2
NakiriFox-LC_Simplified_Chinese_Localization-2.5.0
Skeletonek-LethalLevelLoaderAOORE_Fix-1.3.10
mrov-LightsOut-0.1.3
x753-More_Suits-1.4.3
Shlygly-Juices_Mod-1.4.0
BunyaPineTree-ModelReplacementAPI-2.4.10
LuckyJesta-ArknightsPlayerModel-7.0.1
TShine-ChineseBrideAndNewYearGhostgirl-1.0.2
Wexop-RandomEnemiesSize-1.1.12
etherealemil-UsualScrap-1.6.8
Hamunii-DetourContext_Dispose_Fix-1.0.3
Hamunii-AutoHookGenPatcher-1.0.4
Azim-LethalPresents-1.0.8
loaforc-FacilityMeltdown-2.6.20
jockie-LethalExpansionCore-1.3.15
rainbow137-MinecraftScraps-1.4.3
Sigurd-CSync-5.0.1
Scintesto-Monster_Plushies-1.2.9
Agutrot-MolesterLootBug_Fork-1.0.0
347956-JPOGTrex-1.1.2
no00ob-LCSoundTool-1.5.1
ash123-GXFC_otto-3.0.0
sunnobunno-YippeeMod-1.2.4
347956-JPOGStegosaurus-1.0.1
readthisifbad-SnatchinBracken-1.5.1
Dev1A3-BetterVehicleControls-1.1.3
MiffyL-Kill_It_With_Shovel-1.0.1
Dammsugare-KeepScrap-1.0.0
OpJosMods-ReviveCompany-1.4.0
Goobius-Scary_Coil_Head-1.0.1
xilophor-LethalNetworkAPI-3.3.1
PloufJPEG-Hallucinoceps-0.3.0
Piggy-Piggys_Variety_Mod-1.3.14
LynxDev-OptimizedSkinwalkers-2.3.0
SillySquad-TakeThatMaskOff-2.1.6
chuxiaaaa-UniversalBag-1.0.0
TestAccount666-TestAccountCore-1.8.2
TestAccount666-AutomaticInventoryFixPlugin-1.2.0
GoblinKingShmee-MondstadtMoon-1.0.2
Verity-TooManySuits-2.0.0
DeathWrench-DisableHelmetVisor-0.0.1
Zehs-Hitmarker-1.2.3
coderCleric-Poltergeist-1.1.1
Kittenji-Dont_Touch_Me-1.2.4
TheDeadSnake-Touchscreen-1.1.3
bctix-FPSCounter-1.4.0
LethalCompanyModding-LCUltrawide_Community-1.1.2
Olemyth-Crypt-1.3.5
Garf-MissileTurrets-1.3.5
FlipMods-TooManyEmotes-2.2.7
Bobbie-NAudio-2.2.2
qwbarch-NAudioLame-2.1.1
WhiteSpike-Interactive_Terminal_API-1.1.4
WarperSan-ShipInventory-1.1.4
Zehs-SellMyScrap-1.7.1
actibytes-SkellyGlowSuits-1.0.6
qwbarch-Mirage-1.10.0
Nikki-NikkisCosmeticKingdom-2.0.2
malco-Lategame_Upgrades-3.10.3
AdiBTW-LoadstoneNightly-0.1.14
s1ckboy-Seichi-0.9.2
qwbarch-MirageCore-1.0.1
willis81808-LethalSettings-1.4.0
EliteMasterEric-Coroner-2.2.0
4902-No_Console_Spam-1.5.0
qwcan-LethalExpansionCorePatch-1.3.18
DaXcess-NoJumpDelay-1.0.0
BaronDrakula-MoreCounterplay-1.3.1
NotAtomicBomb-TerminalApi-1.5.5
UnloadedHangar-Brutal_Company_Minus_Extra-0.19.1
EliteMasterEric-CleanerLogs-1.0.0
MelanieMelicious-MelanieMelicious_fAnCy_ShIp-0.0.1
sfDesat-Celestial_Tint-1.5.2
HugotheDwarf-Ammo_Tin_Piggy_Compat-1.0.0
HugotheDwarf-Ammo_Tin-1.1.0
Feiryn-LethalMon-0.6.3

**Comment by Feiryn** [comment]
Most mod managers can export mod packs

![image](https://github.com/user-attachments/assets/94be8452-7dd3-43b4-9aa5-2999d71d9922)

**Comment by lenmon666** [comment]
> 大多数 Mod 管理器都可以导出 Mod 包
> 
> ![image](https://private-user-images.githubusercontent.com/98115666/372525546-94be8452-7dd3-43b4-9aa5-2999d71d9922.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTQ2NzUsIm5iZiI6MTcyNzc5NDM3NSwicGF0aCI6Ii85ODExNTY2Ni8zNzI1MjU1NDYtOTRiZTg0NTItN2RkMy00M2I0LTlhYTUtMjk5OWQ3MWQ5OTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE0NTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZjA0ODMwMmU5YzRkNGY1NTE4NGI1NTg3ZWYwNzU1ODRhMzBlMTBjMzFmYzRhMDVjNjYwOTliNjdlYTI2NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9R10YuI_HnW51CsKitB6oUVGbXXeK-m6TYm49aJg5Bc)
It reminds me that my mod is too large to export!

**Comment by lenmon666** [comment]
> 大多数 Mod 管理器都可以导出 Mod 包
> 
> ![image](https://private-user-images.githubusercontent.com/98115666/372525546-94be8452-7dd3-43b4-9aa5-2999d71d9922.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTUxNjMsIm5iZiI6MTcyNzc5NDg2MywicGF0aCI6Ii85ODExNTY2Ni8zNzI1MjU1NDYtOTRiZTg0NTItN2RkMy00M2I0LTlhYTUtMjk5OWQ3MWQ5OTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE1MDEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYTJmNzQwZjY5NjRkNGQxMjkxZDZlMjYyOTUzN2Q3YWY5NjIxZjVjMTU2ZGNjMzQ4NDUyN2YwY2Q1NzE0MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dnil1vddvFzB7S0ujH6ePAGabvjgGfjc3nbCMamra_8)

Is the mods. yml file useful?

**Comment by Feiryn** [comment]
> Is the mods. yml file useful?

Can you try to export the profile as a file ?

**Comment by lenmon666** [comment]
> > 是 Mod。yml 文件有用吗？
> 
> 您能否尝试将配置文件导出为文件？
Is it the file exported in. r2z format? I looked at all the configuration files inside that only contain mods!

**Comment by lenmon666** [comment]
> > > > 是 Mod。yml 文件有用吗？
> > > 
> > > 
> > > 您能否尝试将配置文件导出为文件？是导出的文件吗？r2z 格式？我查看了里面所有只包含 Mod 的配置文件！
> 
> 是的，请发送 r2z 文件

The file has been uploaded!

**Comment by Feiryn** [comment]
I couldn't reproduce the issue, but I just released version 0.6.4 (coming to thunderstore in about 30 min) that should fix the errors you have.
If it doesn't work please reopen this issue.

**Comment by lenmon666** [comment]
> 我无法重现这个问题，但我刚刚发布了 0.6.4 版本（大约 30 分钟后进入 thunderstore），它应该可以解决您遇到的错误。如果它不起作用，请重新打开此问题。

I have tested playing with my friends using the latest version! I haven't found any error log information on the console anymore!
Thank you very much for your hard work and repair!
