### ISSUE TITLE
IDEA: Purchasing LethalMon balls (thats what I call them)

### ISSUE THREAD

**Issue by tabs4** [Feiryn/LethalMon#6]
Adding the ability to buy them in the store.
Example: The default one cost could be 50 credits.
Example: the ultra could cost 200 credits or more.
etc.
I'd like this to be added since I cant find any of the lethalmon balls :( 

(note I suck at finding loot)

**Comment by NiroDev** [comment]
Implemented in 0.2.1. Config options will follow soon
